namespace LinuxMTAInstaller.Forms {
	partial class TeamspeakWindow {
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose ( bool disposing ) {
			if ( disposing && ( components != null ) ) {
				components.Dispose ();
			}
			base.Dispose ( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent ( ) {
			this.components = new System.ComponentModel.Container();
			this.username = new System.Windows.Forms.TextBox();
			this.label2 = new System.Windows.Forms.Label();
			this.userpw = new System.Windows.Forms.TextBox();
			this.label3 = new System.Windows.Forms.Label();
			this.serveradminpw = new System.Windows.Forms.TextBox();
			this.label1 = new System.Windows.Forms.Label();
			this.button1 = new System.Windows.Forms.Button();
			this.label4 = new System.Windows.Forms.Label();
			this.button2 = new System.Windows.Forms.Button();
			this.error = new System.Windows.Forms.ErrorProvider(this.components);
			((System.ComponentModel.ISupportInitialize)(this.error)).BeginInit();
			this.SuspendLayout();
			// 
			// username
			// 
			this.username.Location = new System.Drawing.Point(136, 12);
			this.username.Name = "username";
			this.username.Size = new System.Drawing.Size(180, 20);
			this.username.TabIndex = 0;
			this.username.Text = "ts";
			// 
			// label2
			// 
			this.label2.Location = new System.Drawing.Point(12, 41);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(118, 13);
			this.label2.TabIndex = 3;
			this.label2.Text = "User-password:";
			this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// userpw
			// 
			this.userpw.Location = new System.Drawing.Point(136, 38);
			this.userpw.Name = "userpw";
			this.userpw.Size = new System.Drawing.Size(180, 20);
			this.userpw.TabIndex = 2;
			// 
			// label3
			// 
			this.label3.Location = new System.Drawing.Point(12, 67);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(118, 13);
			this.label3.TabIndex = 5;
			this.label3.Text = "serveradmin-password:";
			this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// serveradminpw
			// 
			this.serveradminpw.Location = new System.Drawing.Point(136, 64);
			this.serveradminpw.Name = "serveradminpw";
			this.serveradminpw.Size = new System.Drawing.Size(180, 20);
			this.serveradminpw.TabIndex = 4;
			// 
			// label1
			// 
			this.label1.Location = new System.Drawing.Point(12, 15);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(118, 13);
			this.label1.TabIndex = 6;
			this.label1.Text = "Running user:";
			this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// button1
			// 
			this.button1.Location = new System.Drawing.Point(44, 134);
			this.button1.Name = "button1";
			this.button1.Size = new System.Drawing.Size(107, 30);
			this.button1.TabIndex = 7;
			this.button1.Text = "Install";
			this.button1.UseVisualStyleBackColor = true;
			this.button1.Click += new System.EventHandler(this.button1_Click);
			// 
			// label4
			// 
			this.label4.Location = new System.Drawing.Point(15, 87);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(309, 32);
			this.label4.TabIndex = 8;
			this.label4.Text = "If \"serveradmin-password:\" stays blank the password will stay generated by the se" +
    "rver!";
			this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// button2
			// 
			this.button2.Location = new System.Drawing.Point(184, 134);
			this.button2.Name = "button2";
			this.button2.Size = new System.Drawing.Size(107, 30);
			this.button2.TabIndex = 9;
			this.button2.Text = "Back";
			this.button2.UseVisualStyleBackColor = true;
			this.button2.Click += new System.EventHandler(this.button2_Click);
			// 
			// error
			// 
			this.error.ContainerControl = this;
			// 
			// TeamspeakWindow
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(336, 176);
			this.Controls.Add(this.button2);
			this.Controls.Add(this.label4);
			this.Controls.Add(this.button1);
			this.Controls.Add(this.label1);
			this.Controls.Add(this.label3);
			this.Controls.Add(this.serveradminpw);
			this.Controls.Add(this.label2);
			this.Controls.Add(this.userpw);
			this.Controls.Add(this.username);
			this.Name = "TeamspeakWindow";
			this.Text = "Teamspeak Installer";
			((System.ComponentModel.ISupportInitialize)(this.error)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.TextBox username;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.TextBox userpw;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.TextBox serveradminpw;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.Button button1;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.Button button2;
		private System.Windows.Forms.ErrorProvider error;
	}
}